/*
   Generated by ex4-to-mq4 decompiler (forex-warez.com) 4.0.509.5
   Website: Ww w . ForEx- wa r E z . c Om
   E-mail :  aN d R E Ybb R v@G mA IL.cOM
*/
#property copyright " "
#property link      ""

extern double Lots = 0.01;
int Gi_84 = 300;
int Gi_88 = 0;
bool Gi_92 = FALSE;
int Gi_96 = 300;
int Gi_100 = 500;
int Gi_104 = 300;
int Gi_108 = 500;
int Gi_112 = 300;
int Gi_116 = 500;
int Gi_120 = 300;
int Gi_124 = 500;
int Gi_128 = 300;
int Gi_132 = 500;
int Gi_136 = 300;
int Gi_140 = 500;
int Gi_144 = 300;
int Gi_148 = 500;
int Gi_152 = 300;
int Gi_156 = 500;
int Gi_160 = 300;
int Gi_164 = 500;
int Gi_168 = 300;
int Gi_172 = 550;
int Gi_176 = 730;
int Gi_180 = 860;
int Gi_184 = 1000;
int Gi_188 = 1150;
int Gi_192 = 1300;
int Gi_196 = 1450;
int Gi_200 = 1600;
int Gi_204 = 1750;
int Gi_208 = 1900;
int Gi_212 = 2050;
int Gi_216 = 2200;
int Gi_220 = 2350;
int Gi_224 = 2500;
int Gi_228 = 2650;
int Gi_232 = 2800;
int Gi_236 = 30;
int Gi_240 = 2;
int Gi_244 = 0;
int Gi_248 = 24;
extern int Magic = 111;
extern bool CloseAllNow = FALSE;
extern bool UseMACD = FALSE;
extern int BrokerMode = 1;
bool Gi_268 = FALSE;
int Gi_272 = 24;
int Gi_276 = D'01.01.2015 00:00';
int Gi_280 = D'20.05.2029 16:00';
string Gs_284 = "Demo is expired. Visit www.fxpromakerea.com and order FULL version";
string Gs_292 = "Demo is not working on live accounts. Visit www.fxpromakerea.com";
string Gs_300 = "You need to increase your deposit to ";
string Gs_308 = "for trading this lot;";
string Gs_316 = "Or change your lotsize according Manual.";
int Gi_324 = 0;
string Gs_328 = "We recommend you to trade on USDJPY only";

extern string uj="USDJPY-STD";
// E37F0136AA3FFAF149B351F6A4C948E9
int init() {
   //if ((!IsDemo()) && (!IsTesting())) Alert(Gs_292);
   //if (Symbol() != uj) Alert(Gs_328);
   //if (IsTesting() == TRUE) Gi_324 = 5000000;
   //else {
   //   if (AccountLeverage() <= 100) Gi_324 = 5000000;
   //   else Gi_324 = 2500000;
   //}
   //Gi_324 = NormalizeDouble(Gi_324 * Lots, 0);
   //if (AccountBalance() < Gi_324) {
   //   Alert(Gs_300 + Gi_324 + " $" 
   //      + "\n" 
   //      + Gs_308 
   //      + "\n" 
   //   + Gs_316);
   //}
   //return (1);
}

// EA2B2676C28C0DB26D39331A336C6B92
int start() {
   int Li_0;
   int Li_4;
   int Li_8;
   double Ld_12;
   double Ld_20;
   double Ld_28;
   double Ld_36;
   double Ld_44;
   double Ld_52;
   double Ld_60;
   double Ld_68;
   double Ld_76;
   bool Li_84;
   double Ld_88;
   double Ld_96;
   if (Symbol() != uj) {
      Comment(Gs_328);
      return (-1);
   }
   if (AccountBalance() < Gi_324) {
      Comment(Gs_300 + Gi_324 + " $" 
         + "\n" 
         + Gs_308 
         + "\n" 
      + Gs_316);
      //return (-1);
   }
   //if ((!IsDemo()) && (!IsTesting())) {
   //   Comment(Gs_292);
   //   return (-1);
   //}
   if (CloseAllNow == TRUE) {
      for (int Li_104 = OrdersTotal() - 1; Li_104 >= 0; Li_104--) {
         OrderSelect(Li_104, SELECT_BY_POS, MODE_TRADES);
         if (OrderSymbol() == Symbol() || BrokerMode == 3 && OrderMagicNumber() == Magic) {
            if (OrderType() == OP_BUY || OrderType() == OP_SELL) OrderClose(OrderTicket(), OrderLots(), OrderClosePrice(), 5, CLR_NONE);
            if (OrderType() != OP_BUY && OrderType() != OP_SELL) OrderDelete(OrderTicket());
         }
      }
      return (0);
   }
   int Li_108 = 0;
   int Li_112 = 0;
   int Li_116 = 0;
   int Li_120 = 0;
   int Li_124 = 0;
   int Li_128 = 0;
   double Ld_132 = 0;
   double Ld_140 = 0;
   double Ld_148 = 0;
   double Ld_156 = 0;
   double Ld_164 = 0;
   double Ld_172 = 0;
   double Ld_180 = 0;
   double Ld_188 = 0;
   double Ld_196 = 0;
   double Ld_204 = 0;
   double Ld_212 = 0;
   double Ld_220 = 0;
   double Ld_228 = 0;
   double Ld_236 = 0;
   string Ls_244 = "";
   string Ls_252 = "";
   string Ls_260 = "";
   string Ls_268 = "";
   string Ls_276 = "";
   string Ls_284 = "";
   string Ls_292 = "";
   string Ls_300 = "";
   string Ls_308 = "";
   string Ls_316 = "";
   string Ls_324 = "";
   if (Gi_268 == TRUE) Li_4 = 100;
   else Li_4 = 1;
   if (iMACD(NULL, 0, 14, 26, 9, PRICE_CLOSE, MODE_MAIN, 0) > iMACD(NULL, 0, 14, 26, 9, PRICE_CLOSE, MODE_MAIN, 1)) Li_0 = 2;
   if (iMACD(NULL, 0, 14, 26, 9, PRICE_CLOSE, MODE_MAIN, 0) < iMACD(NULL, 0, 14, 26, 9, PRICE_CLOSE, MODE_MAIN, 1)) Li_0 = 1;
   for (int Li_332 = 0; Li_332 < OrdersTotal(); Li_332++) {
      OrderSelect(Li_332, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() == Symbol() || BrokerMode == 3 && OrderMagicNumber() == Magic) {
         if (OrderType() == OP_BUY && OrderLots() > Ld_132) {
            Ld_132 = OrderLots();
            Ld_148 = OrderOpenPrice();
            Li_108 = OrderTicket();
            Ld_172 = OrderTakeProfit();
         }
         if (OrderType() == OP_BUY) {
            if (OrderLots() < Ld_228 || Ld_228 == 0.0) {
               Ld_228 = OrderLots();
               Ld_212 = OrderOpenPrice() - Gi_88 * Point;
            }
         }
         if (OrderType() == OP_SELL && OrderLots() > Ld_140) {
            Ld_140 = OrderLots();
            Ld_156 = OrderOpenPrice();
            Li_112 = OrderTicket();
            Ld_164 = OrderTakeProfit();
         }
         if (OrderType() == OP_SELL) {
            if (OrderLots() < Ld_236 || Ld_236 == 0.0) {
               Ld_236 = OrderLots();
               Ld_220 = OrderOpenPrice() + Gi_88 * Point;
            }
         }
         if (OrderType() == OP_BUYLIMIT) {
            Li_116 = OrderTicket();
            Ld_196 = OrderLots();
         }
         if (OrderType() == OP_SELLLIMIT) {
            Li_120 = OrderTicket();
            Ld_204 = OrderLots();
         }
         if (OrderType() == OP_BUYSTOP) {
            Li_124 = OrderTicket();
            Ld_180 = OrderLots();
         }
         if (OrderType() == OP_SELLSTOP) {
            Li_128 = OrderTicket();
            Ld_188 = OrderLots();
         }
      }
   }
   if (Li_108 == 0 && Li_116 != 0) OrderDelete(Li_116);
   if (Li_108 == 0 && Li_116 == 0) {
      if (TimeCurrent() >= Gi_276 && TimeCurrent() <= Gi_280) {
         if ((Month() > 1 && Month() < 12) || (Month() == 1 && Day() >= 7) || (Month() == 12 && Day() < 20)) {
            Ld_20 = Ask - Gi_88 * Point;
            if (Gi_88 <= 0) Ld_20 = 0;
            Ld_28 = Ask + Gi_84 * Point;
            if ((Gi_244 < Gi_248 && TimeHour(TimeCurrent()) >= Gi_244 && TimeHour(TimeCurrent()) < Gi_248) || (Gi_244 > Gi_248 && TimeHour(TimeCurrent()) >= Gi_244 || TimeHour(TimeCurrent()) < Gi_248)) {
               if (DayOfWeek() != 5 || Hour() < Gi_272) {
                  if ((Li_0 == 2 && Li_112 == 0) || UseMACD == FALSE) {
                     if (AccountFreeMarginCheck(Symbol(), OP_BUY, Lots * Li_4) >= 0.0) {
                        if (BrokerMode != 2 && BrokerMode != 3) OrderSend(Symbol(), OP_BUY, Lots, Ask, Gi_236, Ld_20, Ld_28, "Magic = " + Magic, Magic, 0, CLR_NONE);
                        else {
                           Li_8 = OrderSend(Symbol(), OP_BUY, Lots, Ask, Gi_236, 0, 0, "Magic = " + Magic, Magic, 0, CLR_NONE);
                           if (Li_8 > 0) {
                              Li_84 = OrderModify(Li_8, OrderOpenPrice(), Ld_20, Ld_28, 0, CLR_NONE);
                              if (Li_84 == FALSE) Print("Error modifying BUY order : ", GetLastError());
                           }
                        }
                     } else {
                        if (AccountFreeMarginCheck(Symbol(), OP_BUY, Lots) >= 0.0) Ls_308 = "we recommend you to decrease your start lot or increase deposit";
                        else Ls_260 = "BUY, " + DoubleToStr(Lots, 2) + " lots. ";
                     }
                  }
               }
            }
         } else Ls_252 = Gs_284;
      }
   }
   if (Li_112 == 0 && Li_120 != 0) OrderDelete(Li_120);
   if (Li_112 == 0 && Li_120 == 0) {
      if (TimeCurrent() >= Gi_276 && TimeCurrent() <= Gi_280) {
         if ((Month() > 1 && Month() < 12) || (Month() == 1 && Day() >= 7) || (Month() == 12 && Day() < 20)) {
            Ld_20 = Bid + Gi_88 * Point;
            if (Gi_88 <= 0) Ld_20 = 0;
            Ld_28 = Bid - Gi_84 * Point;
            if ((Gi_244 < Gi_248 && TimeHour(TimeCurrent()) >= Gi_244 && TimeHour(TimeCurrent()) < Gi_248) || (Gi_244 > Gi_248 && TimeHour(TimeCurrent()) >= Gi_244 || TimeHour(TimeCurrent()) < Gi_248)) {
               if (DayOfWeek() != 5 || Hour() < Gi_272) {
                  if ((Li_0 == 1 && Li_108 == 0) || UseMACD == FALSE) {
                     if (AccountFreeMarginCheck(Symbol(), OP_SELL, Lots * Li_4) >= 0.0) {
                        if (BrokerMode != 2 && BrokerMode != 3) OrderSend(Symbol(), OP_SELL, Lots, Bid, Gi_236, Ld_20, Ld_28, "Magic = " + Magic, Magic, 0, CLR_NONE);
                        else {
                           Li_8 = OrderSend(Symbol(), OP_SELL, Lots, Bid, Gi_236, 0, 0, "Magic = " + Magic, Magic, 0, CLR_NONE);
                           if (Li_8 > 0) {
                              Li_84 = OrderModify(Li_8, OrderOpenPrice(), Ld_20, Ld_28, 0, CLR_NONE);
                              if (Li_84 == FALSE) Print("Error modifying SELL order : ", GetLastError());
                           }
                        }
                     } else {
                        if (AccountFreeMarginCheck(Symbol(), OP_SELL, Lots) >= 0.0) Ls_308 = "we recommend you to decrease your start lot or increase deposit";
                        else Ls_268 = "SELL, " + DoubleToStr(Lots, 2) + " lots. ";
                     }
                  }
               }
            }
         } else Ls_252 = Gs_284;
      }
   }
   if (Li_108 != 0 && Li_116 == 0) {
      Ld_52 = f0_1(int(Ld_132 / Ld_228));
      Ld_44 = f0_0(int(Ld_132 / Ld_228));
      Ld_12 = Ld_148 - Ld_52 * Point;
      if (Gi_92 == FALSE) Ld_20 = Ld_12 - Gi_88 * Point;
      else Ld_20 = Ld_212;
      if (Gi_88 <= 0) Ld_20 = 0;
      Ld_28 = Ld_12 + Ld_44 * Point;
      if (Ld_132 < 512.0 * Ld_228) Ld_36 = NormalizeDouble(2.0 * Ld_132, Gi_240);
      else Ld_36 = NormalizeDouble(Ld_132 + Ld_228, Gi_240);
      Li_116 = OrderSend(Symbol(), OP_BUYLIMIT, Ld_36, Ld_12, Gi_236, Ld_20, Ld_28, "Magic = " + Magic, Magic, 0, CLR_NONE);
   }
   if (Li_112 != 0 && Li_120 == 0) {
      Ld_52 = f0_1(int(Ld_140 / Ld_236));
      Ld_44 = f0_0(int(Ld_140 / Ld_236));
      Ld_12 = Ld_156 + Ld_52 * Point;
      if (Gi_92 == FALSE) Ld_20 = Ld_12 + Gi_88 * Point;
      else Ld_20 = Ld_220;
      if (Gi_88 <= 0) Ld_20 = 0;
      Ld_28 = Ld_12 - Ld_44 * Point;
      if (Ld_140 < 512.0 * Ld_236) Ld_36 = NormalizeDouble(2.0 * Ld_140, Gi_240);
      else Ld_36 = NormalizeDouble(Ld_140 + Ld_236, Gi_240);
      Li_120 = OrderSend(Symbol(), OP_SELLLIMIT, Ld_36, Ld_12, Gi_236, Ld_20, Ld_28, "Magic = " + Magic, Magic, 0, CLR_NONE);
   }
   if (Li_124 != 0 && Ld_180 <= Ld_132 || Ld_180 == Ld_196) OrderDelete(Li_124);
   if (Ld_228 != 0.0) Ld_52 = f0_1(int(Ld_132 / Ld_228));
   if (Li_108 != 0 && Ld_148 - Ask > Ld_52 * Point && Li_116 <= 0 || Li_124 == 0) {
      Ld_12 = Ld_148 - Ld_52 * Point;
      Ld_76 = Ask;
      while (Ld_12 >= Ld_76) {
         Ld_88 = Ld_132;
         if (Ld_132 < 512.0 * Ld_228) Ld_132 = NormalizeDouble(2.0 * Ld_132, Gi_240);
         else Ld_132 = NormalizeDouble(Ld_132 + Ld_228, Gi_240);
         Ld_52 = f0_1(int(Ld_132 / Ld_228));
         Ld_12 -= Ld_52 * Point;
         if (Ld_12 < Ld_76) {
            if (Li_116 <= 0) {
               Li_116 = -2;
               Ld_44 = f0_0(int(Ld_132 / Ld_228));
               if (Gi_92 == FALSE) Ld_20 = Ld_12 - Gi_88 * Point;
               else Ld_20 = Ld_212;
               if (Gi_88 <= 0) Ld_20 = 0;
               Ld_28 = Ld_12 + Ld_44 * Point;
               if (Ld_132 < 512.0 * Ld_228) Ld_36 = NormalizeDouble(2.0 * Ld_132, Gi_240);
               else Ld_36 = NormalizeDouble(Ld_132 + Ld_228, Gi_240);
               if (AccountFreeMarginCheck(Symbol(), OP_BUY, Ld_36) >= 0.0) Li_116 = OrderSend(Symbol(), OP_BUYLIMIT, Ld_36, Ld_12, Gi_236, Ld_20, Ld_28, "Magic = " + Magic, Magic, 0, CLR_NONE);
               else Ls_316 = "BUYLIMIT, " + DoubleToStr(Ld_36, 2) + " lots. ";
            }
            if (Li_124 == 0 && Ld_132 != Ld_196 && Li_116 != -2) {
               Ld_60 = Ld_12 + Ld_52 * Point;
               Ld_44 = f0_0(int(Ld_88 / Ld_228));
               Ld_28 = Ld_60 + Ld_44 * Point;
               Ld_36 = NormalizeDouble(Ld_132, Gi_240);
               if (Gi_92 == FALSE) Ld_20 = Ld_60 - Gi_88 * Point;
               else Ld_20 = Ld_212;
               if (Gi_88 <= 0) Ld_20 = 0;
               Li_8 = OrderSend(Symbol(), OP_BUYSTOP, Ld_36, Ld_60, Gi_236, Ld_20, Ld_28, "Magic = " + Magic, Magic, 0, CLR_NONE);
            }
         }
      }
   }
   if (Li_128 != 0 && Ld_188 <= Ld_140 || Ld_188 == Ld_204) OrderDelete(Li_128);
   if (Ld_236 != 0.0) Ld_52 = f0_1(int(Ld_140 / Ld_236));
   if (Li_112 != 0 && Bid - Ld_156 > Ld_52 * Point && Li_120 <= 0 || Li_128 == 0) {
      Ld_12 = Ld_156 + Ld_52 * Point;
      Ld_76 = Bid;
      while (Ld_12 <= Ld_76) {
         if(Ld_236<=0) Ld_236 = 1;//++
         Ld_96 = Ld_140;
         if (Ld_140 < 512.0 * Ld_236) Ld_140 = NormalizeDouble(2.0 * Ld_140, Gi_240);
         else Ld_140 = NormalizeDouble(Ld_140 + Ld_236, Gi_240);
         //Ld_52 = f0_1(NormalizeDouble(Ld_140 / Ld_236, 0));
         Ld_52 = f0_1(int(Ld_140 / Ld_236));
         Ld_12 += Ld_52 * Point;
         if (Ld_12 > Ld_76) {
            if (Li_120 <= 0) {
               Li_120 = -2;
               Ld_44 = f0_0(int(Ld_140 / Ld_236));
               if (Gi_92 == FALSE) Ld_20 = Ld_12 + Gi_88 * Point;
               else Ld_20 = Ld_220;
               if (Gi_88 <= 0) Ld_20 = 0;
               Ld_28 = Ld_12 - Ld_44 * Point;
               if (Ld_140 < 512.0 * Ld_236) Ld_36 = NormalizeDouble(2.0 * Ld_140, Gi_240);
               else Ld_36 = NormalizeDouble(Ld_140 + Ld_236, Gi_240);
               if (AccountFreeMarginCheck(Symbol(), OP_SELL, Ld_36) >= 0.0) Li_120 = OrderSend(Symbol(), OP_SELLLIMIT, Ld_36, Ld_12, Gi_236, Ld_20, Ld_28, "Magic = " + Magic, Magic, 0, CLR_NONE);
               else Ls_324 = "SELLLIMIT, " + DoubleToStr(Ld_36, 2) + " lots. ";
            }
            if (Li_128 == 0 && Ld_140 != Ld_204 && Li_120 != -2) {
               Ld_68 = Ld_12 - Ld_52 * Point;
               Ld_44 = f0_0(int(Ld_96 / Ld_236));
               Ld_28 = Ld_68 - Ld_44 * Point;
               Ld_36 = NormalizeDouble(Ld_140, Gi_240);
               if (Gi_92 == FALSE) Ld_20 = Ld_68 + Gi_88 * Point;
               else Ld_20 = Ld_220;
               if (Gi_88 <= 0) Ld_20 = 0;
               Li_8 = OrderSend(Symbol(), OP_SELLSTOP, Ld_36, Ld_68, Gi_236, Ld_20, Ld_28, "Magic = " + Magic, Magic, 0, CLR_NONE);
            }
         }
      }
   }
   for (Li_332 = 0; Li_332 < OrdersTotal(); Li_332++) {
      OrderSelect(Li_332, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() == Symbol() || BrokerMode == 3 && OrderType() == OP_BUY && Li_108 != 0 && OrderMagicNumber() == Magic) {
         if (Gi_92 == FALSE) Ld_20 = Ld_148 - Gi_88 * Point;
         else Ld_20 = Ld_212;
         if (Gi_88 <= 0) Ld_20 = 0;
         if (OrderLots() < Ld_132) Ld_28 = Ld_172;
         else Ld_28 = OrderTakeProfit();
         if (Ld_28 != OrderTakeProfit() || Ld_20 != OrderStopLoss()) OrderModify(OrderTicket(), OrderOpenPrice(), Ld_20, Ld_28, 0, CLR_NONE);
      }
      if (OrderSymbol() == Symbol() || BrokerMode == 3 && OrderType() == OP_SELL && Li_112 != 0 && OrderMagicNumber() == Magic) {
         if (Gi_92 == FALSE) Ld_20 = Ld_156 + Gi_88 * Point;
         else Ld_20 = Ld_220;
         if (Gi_88 <= 0) Ld_20 = 0;
         if (OrderLots() < Ld_140) Ld_28 = Ld_164;
         else Ld_28 = OrderTakeProfit();
         if (Ld_28 != OrderTakeProfit() || Ld_20 != OrderStopLoss()) OrderModify(OrderTicket(), OrderOpenPrice(), Ld_20, Ld_28, 0, CLR_NONE);
      }
   }
   if (Ls_260 != "" || Ls_268 != "" || Ls_276 != "" || Ls_284 != "" || Ls_292 != "" || Ls_300 != "" || Ls_316 != "" || Ls_324 != "") Ls_244 = "Not enough margin for opening orders: ";
   Comment(Ls_252, 
      "\n", Ls_244, Ls_260, Ls_268, Ls_276, Ls_284, Ls_292, Ls_300, Ls_316, Ls_324, 
   "\n", Ls_308);
   return (0);
}

// 20A91EADFB1ED541FAB72DD08652A9C7
int f0_1(int Ad_0) {
   switch (Ad_0) {
   case 1 :
      return (Gi_96);
   case 2 :
      return (Gi_104);
   case 4 :
      return (Gi_112);
   case 8 :
      return (Gi_120);
   case 16 :
      return (Gi_128);
   case 32 :
      return (Gi_136);
   case 64 :
      return (Gi_144);
   case 128 :
      return (Gi_152);
   case 256 :
      return (Gi_160);
   case 512 :
      return (Gi_168);
   }
   return (Gi_168);
}

// 20252D8ADC9A5D3B861864B8367D5D89
int f0_0(int Ad_0) {
   switch (Ad_0) {
   case 1 :
      return (Gi_100);
   case 2 :
      return (Gi_108);
   case 4 :
      return (Gi_116);
   case 8 :
      return (Gi_124);
   case 16 :
      return (Gi_132);
   case 32 :
      return (Gi_140);
   case 64 :
      return (Gi_148);
   case 128 :
      return (Gi_156);
   case 256 :
      return (Gi_164);
   case 512 :
      return (Gi_172);
   case 513 :
      return (Gi_176);
   case 514 :
      return (Gi_180);
   case 515 :
      return (Gi_184);
   case 516 :
      return (Gi_188);
   case 517 :
      return (Gi_192);
   case 518 :
      return (Gi_196);
   case 519 :
      return (Gi_200);
   case 520 :
      return (Gi_204);
   case 521 :
      return (Gi_208);
   case 522 :
      return (Gi_212);
   case 523 :
      return (Gi_216);
   case 524 :
      return (Gi_220);
   case 525 :
      return (Gi_224);
   case 526 :
      return (Gi_228);
   case 527 :
      return (Gi_232);
   }
   return (Gi_232);
}
